Feature/crawling
Lotte-SweetPotatos/WARr-Cinema pull request #13
Opened 2022-07-09 06:13 UTC by ksh9409255

2022-07-09 06:13 UTC, devpoooh approved these changes, later dismissed

2022-07-09 06:15 UTC, ohjiwon-201733026 approved these changes, later dismissed

2022-07-09 06:43 UTC, NamHyeop commented on Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/movieDetail.jsp
> +<%@ page language="java" contentType="text/html; charset=EUC-KR"
왜 charset=UTF-8에서 EUC-KR로 바뀐건가요?

2022-07-09 06:47 UTC, NamHyeop commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +		String[] moviesNum = { "85999", "82120", "85871", "85997", "85857" };
의미 설명 부탁드려요!

2022-07-09 06:49 UTC, NamHyeop commented on Lotte_SweetPatatos_Warr-Cinema/src/db/DBConnection.java
> +		String url = "jdbc:mysql://localhost:3306/moviedb";
조별로 Database 이름 맞춰야 할 꺼 같습니다.

2022-07-09 07:01 UTC, soulgchoi requested changes
몇가지 코멘트 남겨봤습니다! 다른건 괜찮은데 개행 같은건 컨벤션을 맞췄으니 전체적인 가독성을 위해 수정 부탁해용🥺

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/movieDetail.jsp
> +</tr>
하드코딩된 데이터는 필요 없지 않을까요?

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +	private static Crawling craw = new Crawling();
개행해주세요!

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +	public static Crawling getInstance() {
여기랑 아래에도 전부 메서드 사이마다 개행해주세요!

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +			System.out.println("영화제목: " + titles.text());
프린트문 없어도 될 것 같아용

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +		List<MovieDto> list = new ArrayList<>();
list 라는 이름은 어떤 정보가 담겨있는지 알기 어려울 것 같아요. `movies` 나 `movieDtos` 같은 이름이 더 낫지 않을까요?

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +	public List<MovieDto> test() throws IOException {
이 메서드 이름은 `test`가 맞나요? 실제로 데이터를 크롤링 하는 부분인걸로 보이는데 한 눈에 기능을 알 수 있는 네이밍이면 좋겠습니당🥺

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +		return list;
지금 이대로 하셔도 괜찮은데요, `방어적 복사` 라는 부분을 알면 좋을 것 같아요!
```suggestion
		return new ArrayList<>(movies);
```

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDetailDao.java
> +	private static MovieDetailDao movieDetailDao = new MovieDetailDao();
개행!

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDetailDao.java
> +	public void find(long id) {
id로 영화를 조회해서 리턴하는 메서드 아닌가요? 리턴값이 `void`라면 의미가 없는 걸로 보이네요....

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDetailDao.java
> +	public List<MovieDto> findAll() {
개행!

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDetailDao.java
> +	public boolean insertData(List<MovieDto> dto) {
`insert` 혹은 `create`, `add` 정도면 충분한 이름일 것 같아요.

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDetailDao.java
> +		try {
아래 메서드와 개행에 일관성이 없어요.

2022-07-09 07:01 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/dto/MovieDto.java
> +	public void setId(long id) {
저희 setter 메서드는 사용하지 않으니 없는 게 안전할 것 같습니당! 전부 지워주시길...

2022-07-09 07:06 UTC, devpoooh commented on Lotte_SweetPatatos_Warr-Cinema/WebContent/movie/movieDetail.jsp
> +<%@ page language="java" contentType="text/html; charset=EUC-KR"
수정하겠습니다..

2022-07-09 07:08 UTC, soulgchoi commented
그리고 커밋 메시지는 앞으로 컨벤션에 맞게 잘 남겨주시길 바랍니다!

2022-07-09 07:18 UTC, NamHyeop requested changes
pq 다시 부탁드려요!

2022-07-10 23:37 UTC, soulgchoi reviewed
잘 반영해주셨네요~ 하지만 불필요한 개행이 너무 많아졌고, 커밋  메시지가 단순해서 커밋만 보고는 어떤 부분을 수정한건지 알기 어려웠습니다~

2022-07-10 23:37 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/Crawling.java
> +
메서드 내부에서는 유의미한 개행만 하면 됩니다!ㅎㅎ

2022-07-10 23:37 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/crawling/DataController.java
> +
개행이 너무 많아도 코드 길이가 길어지고, 읽는 사람에게 혼동을 줄 수도 있겠죵..?!!

2022-07-10 23:37 UTC, soulgchoi commented on Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
> +	public MovieDao() {
`private`으로 줘야 할 것 같네요~ 외부에서 `getInstance()`를 쓰지 않고 생성자를 호출할 수도 있으니까요

2022-07-10 23:38 UTC, soulgchoi approved these changes

2022-07-11 00:07 UTC, NamHyeop approved these changes

2022-07-11 00:22 UTC, ksh9409255 commented on Lotte_SweetPatatos_Warr-Cinema/src/dao/MovieDao.java
> +	public MovieDao() {
반영하겠습니다!

2022-07-11 00:32 UTC, ohjiwon-201733026 approved these changes

2022-07-11 00:46 UTC, devpoooh approved these changes

2022-07-11 00:46 UTC, merged